#include "draw.h"
#include "gba.h"
#include "logic.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"
#include "images/coin.h"
#include "images/Bomb.h"
#include "images/gamescreen.h"
// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);
// static void drawCoins(coin coins[5]);
// static void drawBombs(bomb bombs[3]);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    // drawCoins(state->coins);
    // drawBombs(state->bombs);
   UNUSED(state);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// static void drawCoins(coin coins[5]) {
// 	for(int i = 0; i < 5; i++) {
// 		drawImageDMA(coins[i].x, coins[i].y, 15, 15, Coin);
// 	}
// }

// static void drawBombs(bomb bombs[3]) {
// 	for (int i = 0; i < 2; i++) {
// 		drawImageDMA(bombs[i].x, bombs[i].y, 15, 15, Bomb);
// 	}
// }