#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/startScreen.h"
#include "images/coin.h"
#include "images/gamescreen.h"
#include "images/player.h"
#include "images/winScreen.h"
#include "images/failScreen.h"


#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;


    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the start state here.
                //drawFullScreenImageDMA(garbage);
                drawFullScreenImageDMA(StartScreen);
                state = START_NODRAW;

                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = APP_INIT;
                }

                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);
                nextAppState = currentAppState;

                // Draw the initial state of the app
                // fullDrawAppState(&currentAppState);
                drawFullScreenImageDMA(GameScreen);
                drawImageDMA(currentAppState.playerxLocation, currentAppState.playeryLocation, 20, 20, Player);
                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }

                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                int movedRight = currentAppState.playerxLocation < nextAppState.playerxLocation;
                int movedLeft = currentAppState.playerxLocation > nextAppState.playerxLocation;
                int movedDown = currentAppState.playeryLocation < nextAppState.playeryLocation;
                int movedUp = currentAppState.playeryLocation > nextAppState.playeryLocation;

                //Check where player moved and cover its trail
                if (movedDown) {
                    drawRectDMA(nextAppState.playerxLocation, nextAppState.playeryLocation - 1, 20, 1, CUSTOM);
                } 
                if (movedUp) {
                    drawRectDMA(nextAppState.playerxLocation, nextAppState.playeryLocation + 20, 20, 1, CUSTOM);
                }
                if (movedRight) {
                    drawRectDMA(nextAppState.playerxLocation - 1, nextAppState.playeryLocation, 1, 20, CUSTOM);
                }
                if (movedLeft) {
                    drawRectDMA(nextAppState.playerxLocation + 20, nextAppState.playeryLocation, 1, 20, CUSTOM);
                }

                int whichCoin = 10;
                if (vBlankCounter % 15 == 0) {
                    whichCoin = checkForCollisions(&nextAppState);
                    if (whichCoin != 10) {
                        coverCoin(&nextAppState, whichCoin);
                        whichCoin = 10;
                    }
                }

                nextAppState.gameOver = checkForBombs(&nextAppState);

                //Draw player in new location
                drawImageDMA(nextAppState.playerxLocation, nextAppState.playeryLocation, 20, 20, Player);

                if (nextAppState.numOfCoinsCollected == 4) {
                    nextAppState.gameOver = 1;
                }

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver == 1) {
                    currentAppState = nextAppState;
                    state = APP_EXIT;
                }

                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }                 

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;
                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the exit / gameover screen
                if (currentAppState.numOfCoinsCollected == 4) {
                    drawImageDMA(40, 40, 161, 80, WinScreen);
                } else {
                    drawImageDMA(40, 40, 162, 80, FailScreen);
                }
                

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen
                if (KEY_DOWN(BUTTON_START, currentButtons)) {
                    state = START;
                }
                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }
                break;
        }
        
    

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
